# site settings
title: Nathan
subtitle: M. Lui
email: nathanlui95@gmail.com
description: Physical organic chemist by day, <br>flâneur, photographer, and future masterchef by night
# baseurl: # the subpath of your site, e.g. /blog
# url: # the base hostname & protocol for your site
author: Nathan M. Lui
street_address: Baker Lab, Cornell University
city: Ithaca
state: New York
zip_code: 14850
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  # Envelope: mailto:nathanlui95@gmail.com    
  GitHub: https://github.com/thisisntnathan
  Instagram: https://www.instagram.com/this.isnt.nathan/
  flickr: https://www.flickr.com/photos/104282893@N02/
  Google: https://scholar.google.com/citations?user=oTX1IDAAAAAJ&hl=en&oi=ao
  LinkedIn: https://www.linkedin.com/in/nathanmlui
  orcid: https://orcid.org/0000-0003-4950-0914

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
